import { FileSystemItem } from "@/app/interfaces/FileSystemItem";
export const fileSystemItems: FileSystemItem[] = [
  {
    id: "folder1",
    name: "Folder 1",
    isFolder: true,
    isSelected: false,
    isOpen: false,
    children: [
      {
        id: "file1",
        name: "File 1",
        isFolder: false,
        isSelected: false,
        isOpen: false,
      },
      {
        id: "file2",
        name: "File 2",
        isFolder: false,
        isSelected: false,
        isOpen: false,
      },
      {
        id: "folder1-subfolder1",
        name: "Subfolder 1",
        isFolder: true,
        isSelected: false,
        isOpen: false,
        children: [
          {
            id: "file3",
            name: "File 3",
            isFolder: false,
            isSelected: false,
            isOpen: false,
          },
          {
            id: "file4",
            name: "File 4",
            isFolder: false,
            isSelected: false,
            isOpen: false,
          },
        ],
      },
    ],
  },
  {
    id: "folder2",
    name: "Folder 2",
    isFolder: true,
    isSelected: false,
    isOpen: false,
    children: [
      {
        id: "file5",
        name: "File 5",
        isFolder: false,
        isSelected: false,
        isOpen: false,
      },
      {
        id: "folder2-subfolder1",
        name: "Subfolder 1",
        isFolder: true,
        isSelected: false,
        isOpen: false,
        children: [
          {
            id: "file6",
            name: "File 6",
            isFolder: false,
            isSelected: false,
            isOpen: false,
          },
          {
            id: "folder2-subfolder1-subfolder1",
            name: "Nested Subfolder",
            isFolder: true,
            isSelected: false,
            isOpen: false,
            children: [
              {
                id: "file7",
                name: "File 7",
                isFolder: false,
                isSelected: false,
                isOpen: false,
              },
            ],
          },
        ],
      },
      {
        id: "file8",
        name: "File 8",
        isFolder: false,
        isSelected: false,
        isOpen: false,
      },
    ],
  },
  {
    id: "folder3",
    name: "Folder 3",
    isFolder: true,
    isSelected: false,
    isOpen: false,
    children: [
      {
        id: "file9",
        name: "File 9",
        isFolder: false,
        isSelected: false,
        isOpen: false,
      },
      {
        id: "file10",
        name: "File 10",
        isFolder: false,
        isSelected: false,
        isOpen: false,
      },
    ],
  },
  {
    id: "file11",
    name: "File 11",
    isFolder: false,
    isSelected: false,
    isOpen: false,
  },
  {
    id: "folder4",
    name: "Folder 4",
    isFolder: true,
    isSelected: false,
    isOpen: false,
    children: [
      {
        id: "file12",
        name: "File 12",
        isFolder: false,
        isSelected: false,
        isOpen: false,
      },
      {
        id: "folder4-subfolder1",
        name: "Subfolder 1",
        isFolder: true,
        isSelected: false,
        isOpen: false,
        children: [
          {
            id: "file13",
            name: "File 13",
            isFolder: false,
            isSelected: false,
            isOpen: false,
          },
          {
            id: "file14",
            name: "File 14",
            isFolder: false,
            isSelected: false,
            isOpen: false,
          },
        ],
      },
    ],
  },
];
